prog3_server: prog3_server.c prog3_participant prog3_observer
	gcc -ggdb -Wextra -o prog3_server prog3_server.c


prog3_participant: prog3_participant.c
	gcc -ggdb -Wextra -o prog3_participant prog3_participant.c


prog3_observer: prog3_observer.c
	gcc -ggdb -Wextra -o prog3_observer prog3_observer.c
